on:
  pull_request:
    - workflows: cicd-test
      filter:
        source_branches: "feature/**"
        target_branches: [ main ]
        paths: "src/**"
  push:
    - workflows: cicd-integration
      filter:
        branches: [ feature/** ]
        paths: "src/**"
    - workflows: cicd-prod
      filter:
        branches: [ main ]
        paths: "src/**"

workflows:
  cicd-integration:
    tasks:
      - name: deploy-latest
        cubes:
          - name: deploy-function
            env:
              YC_AUTHORIZED_KEY_JSON: ${{ secrets.authorized-key }}
              YC_FOLDER_ID: b1g6sg9nc4qe7eg9lidc
              YC_FUNCTION_NAME: library-prod
              YC_FUNCTION_RUNTIME: nodejs22
              YC_FUNCTION_ENTRYPOINT: index.handler
              YC_FUNCTION_MEMORY: 128m
              YC_FUNCTION_SOURCE_PATH: .
              INCLUDE_PATTERN: "*"
              EXCLUDE_PATTERN: ""
            image: cr.yandex/sourcecraft-cube/yc-function:preview
  cicd-test:
    tasks:
      - name: deploy-latest
        cubes:
          - name: deploy-function
            env:
              YC_AUTHORIZED_KEY_JSON: ${{ secrets.authorized-key }}
              YC_FOLDER_ID: b1g6sg9nc4qe7eg9lidc
              YC_FUNCTION_NAME: library-integration
              YC_FUNCTION_RUNTIME: nodejs22
              YC_FUNCTION_ENTRYPOINT: index.handler
              YC_FUNCTION_MEMORY: 128m
              YC_FUNCTION_SOURCE_PATH: .
              INCLUDE_PATTERN: "*"
              EXCLUDE_PATTERN: ""
            image: cr.yandex/sourcecraft-cube/yc-function:preview
  cicd-prod:
    tasks:
      - name: deploy-latest
        cubes:
          - name: deploy-function
            env:
              YC_AUTHORIZED_KEY_JSON: ${{ secrets.authorized-key }}
              YC_FOLDER_ID: b1g6sg9nc4qe7eg9lidc
              YC_FUNCTION_NAME: library-test
              YC_FUNCTION_RUNTIME: nodejs22
              YC_FUNCTION_ENTRYPOINT: index.handler
              YC_FUNCTION_MEMORY: 128m
              YC_FUNCTION_SOURCE_PATH: .
              INCLUDE_PATTERN: "*"
              EXCLUDE_PATTERN: ""
            image: cr.yandex/sourcecraft-cube/yc-function:preview