# api-gateway.yaml
openapi: 3.0.0
info:
  title: library-api
  version: 1.0.0
paths:
  /api/{proxy+}:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: <ID_КОНТЕЙНЕРА>
      cors:
        origin: '*'
        methods: '*'